### ISSUE TITLE
Homepage Header Redo

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#208]
- [x] BACKGROUND IMAGE FADED

- [x] BOX 1: Welcome (Cliff Image Thumbnail for Video)
Subtitle: About Cliff & Mission

- [x] BOX 2: Start Free 
Pop Up contents move to a a box

- [x] BOX 3: 2 Up / Split Box
Buy E-Courses 
Anytime. Anywhere. Your Pace.

Book Cliff Live 
Speaker & Facilitator
Forums & Retreats

**Comment by sethrubenstein** [comment]
@cliffmichaelsgithub Go ahead and take a look at the site and let me know if you like that or have any changes articulate them well in this ticket.

**Comment by sethrubenstein** [comment]
It's currently 12:09 am on the east coast so I'm going to bed for the night.

**Comment by cliffmichaelsgithub** [comment]
Pretty good. Close!
- [ ] can border / frame around the welcome video be nicer (thicker / or shadow - nicer effect)?
- [ ] can the border / frame  the buy e-courses / book cliff boxes) (thicker / or shadow - nicer effect)?
- [ ] sign up - want to tighten that up a bit > 
![screen shot 2015-02-13 at 9 21 15 pm](https://cloud.githubusercontent.com/assets/6202539/6198672/6c7df358-b3c6-11e4-8efa-6740c1c95e62.png)

**Comment by sethrubenstein** [comment]
K. I can get these done tomorrow morning.

**Comment by cliffmichaelsgithub** [comment]
Thx. Relatively easy tweaks ? As you know by now, I'm highly visual on colors, look & feel + user experience intuitive. You're actually very good when I figure out what I want -- LOL! Sorry for the OCD part.  I think this will work for a proper launch

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 14, 2015, at 11:54 AM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


K. I can get these done tomorrow morning.

-

**Comment by cliffmichaelsgithub** [comment]
Re: iPhone >> current size of the red submit button is too wide on iPhone. Maybe shorten from 

"Submit Now to Access Account"
To
"Submit for FREE LEARNING!"

**Comment by sethrubenstein** [comment]
This is all complete. The items left unchecked were just not doable or couldn't fit. 

The request to make the signup area into a box made the entire header just to crowded and also made it impossible to fit the signup form and such in there adequately as a box has to have padding so its content doesnt touch the edges of the box thus decreasing the interior space of the box.

 Also making all the boxes the same size was out of the question because you have 1 box on the left and then 2 boxes on the right - also because if a user is logged in the signup form changes slightly in that they dont see the facebook signup that changes the height of the middle area. So theres no real good way to match heights across that area. 

That said i've really tightened up the signup form area so its as short as possible and ive made the left box and the 2 right boxes manually as close in height as possible so theres a symmetry going on between all 3 boxes with the middle one being taller and signifying its importance to the user exactly because it is slightly different.

**Comment by cliffmichaelsgithub** [comment]
Re: the clean up looks a little less busy - thanks - I can't tell quote from cell phone - can review later >>  Start Free (remove word "learning") it takes up too much space. Just "Start Free" on top and "Submit to Start Free" in the  red button











On Feb 16, 2015, at 7:36 AM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


This is all complete. The items left unchecked were just not doable or couldn't fit.

The request to make the signup area into a box made the entire header just to crowded and also made it impossible to fit the signup form and such in there adequately as a box has to have padding so its content doesnt touch the edges of the box thus decreasing the interior space of the box.

Also making all the boxes the same size was out of the question because you have 1 box on the left and then 2 boxes on the right - also because if a user is logged in the signup form changes slightly in that they dont see the facebook signup that changes the height of the middle area. So theres no real good way to match heights across that area.

That said i've really tightened up the signup form area so its as short as possible and ive made the left box and the 2 right boxes manually as close in height as possible so theres a symmetry going on between all 3 boxes with the middle one being taller and signifying its importance to the user exactly because it is slightly different.

-
