### ISSUE TITLE
Migrate from Zapier to Outlook

### ISSUE THREAD

**Issue by sethrubenstein** [PixelRocket-Biz/cliff-michaels#226]

**Comment by sethrubenstein** [comment]
Okay @cliffmichaelsgithub new customers and new signups are now feeding into your Outlook contact book.

**Comment by cliffmichaelsgithub** [comment]
Great thanks!

**Comment by cliffmichaelsgithub** [comment]
Do we kill the two Zoho services and get mail chimp

**Comment by sethrubenstein** [comment]
Yea go ahead and cancel your Zoho account and signup for a mailchimp account. Email your mailchimp details and I'll setup a link so that outlook contacts get fed to Mailchimp.

**Comment by cliffmichaelsgithub** [comment]
Did whatever was in Zoho go into outlook?

Cliff > 310-488-6422
VC | Mortgages | Private Equity
Real Estate Investments
CliffMichaels.com<http://cliffmichaels.com/funding><http://cliffmichaels.com/funding>/<http://cliffmichaels.com/funding>Funding<http://cliffmichaels.com/funding>
Coach | Speaker | Facilitator
E-Courses | Forums | Retreats
Career & Entrepreneurial Training
CliffMichaels.com<http://cliffmichaels.com/> | LinkedIN<http://linkedin.com/in/cliffmichaels>









On Feb 25, 2015, at 7:25 PM, Seth Rubenstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Yea go ahead and cancel your Zoho account and signup for a mailchimp account. Email your mailchimp details and I'll setup a link so that outlook contacts get fed to Mailchimp.

-

**Comment by sethrubenstein** [comment]
Probably not, keep it open till Monday I'll go in and run an export.
